const MessageType = {
  COPY_FROM_CREDENTIALS: 'COPY_FROM_CREDENTIALS',
  POPULATE_CREDENTIALS: 'POPULATE_CREDENTIALS',
  INSERT_LOGIN: 'INSERT_LOGIN',
  UPDATE_LOGIN: 'UPDATE_LOGIN',
  DELETE_LOGIN: 'DELETE_LOGIN',
  DELETE_ALL_LOGINS: 'DELETE_ALL_LOGINS',
  MOVE_LOGINS: 'MOVE_LOGINS'
}

export default MessageType
